language: node_js
node_js:
  - node

before_install: yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script:
  - yarn build

after_script: greenkeeper-lockfile-upload

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  fqdn: headless.ninja
  email: bot@headless.ninja
  name: Headless Ninja Bot
  on:
    branch: master